# Generated by Django 3.2.7 on 2021-09-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='age',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='location',
            field=models.CharField(default='asd', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.CharField(default='asdf', max_length=10),
            preserve_default=False,
        ),
    ]
